# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91f9ba6455c9cf39748037dbf2b5dd74814bae38a384dcce2cd69a58d18acc2b5235a2796a316ca972c3edb47077c619f1e5e1fd76006fa4f29d8053160d69f0

test:
  secret_key_base: 738cb2bdde6b3d21e785fb51b49cb82412fb5df13e1f79b840f5a7646a7274b0b7d9832257aed1a7678e92683d04c6ea2ab26727cec820e1f500929c4053b7c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
